### ISSUE TITLE
Relying on imports of user

### ISSUE THREAD

**Issue by 2Math0** [2Math0/codewars-challenges#2]
### HTML dynamic color string generation
 in **Test Cases**
_reported_  an issue from code-wars discourse [here](https://www.codewars.com/kata/56f1c6034d0c330e4a001059/discuss/python) .

```
Traceback (most recent call last):
  File "/workspace/default/src/codewars-test/codewars_test/test_framework.py", line 111, in wrapper
    func()
  File "tests.py", line 41, in bunch_in_a_row_case
    random.seed(i)
NameError: name 'random' is not defined
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by 2Math0** [comment]
fixed in this  **[commit](https://github.com/2Math0/codewars-challenges/commit/f8b1d46b624643c205572fa3d4693a4595b3b882)**.
